import { UserError } from '@openai/agents-core';
import { loadEnv, randomUUID } from '@openai/agents-core/_shims';
import {
  Manifest,
  SandboxProviderError,
  SandboxUnsupportedFeatureError,
  SandboxWorkspaceArchiveReadError,
  SandboxWorkspaceReadNotFoundError,
  normalizeSandboxClientCreateArgs,
  type SandboxClient,
  type SandboxClientCreateArgs,
  type SandboxClientOptions,
  type SandboxArchiveLimits,
  type SandboxConcurrencyLimits,
  type ExposedPortEndpoint,
  type ExecCommandArgs,
  type Mount,
  type SandboxSessionLifecycleOptions,
  type SandboxSessionState,
  type TypedMount,
  type WriteStdinArgs,
} from '@openai/agents-core/sandbox';
import {
  addPtyWebSocketListener,
  appendPtyOutput,
  assertCoreSnapshotUnsupported,
  assertResumeRecreateAllowed,
  createPtyProcessEntry,
  assertSandboxManifestMetadataSupported,
  SANDBOX_MANIFEST_METADATA_SUPPORT,
  assertRunAsUnsupported,
  closeRemoteSessionOnManifestError,
  assertShellEnvironmentName,
  deserializeRemoteSandboxSessionStateValues,
  formatPtyExecUpdate,
  materializeEnvironment,
  openPtyWebSocket,
  parseExposedPortEndpoint,
  posixDirname,
  providerErrorMessage,
  resolveSandboxWorkdir,
  serializeRemoteSandboxSessionState,
  shellQuote,
  shellCommandForPty,
  toUint8Array,
  markPtyDone,
  writePtyStdin,
  isRecord,
  readOptionalBoolean,
  readOptionalNumber,
  readOptionalRecordArray,
  readOptionalString,
  readOptionalStringRecord,
  readString,
  withProviderError,
  withSandboxSpan,
  PtyProcessRegistry,
  RemoteSandboxSessionBase,
  type RemoteSandboxCommandOptions,
  type RemoteSandboxCommandResult,
  type PtyProcessEntry,
} from '../shared';
import {
  isBlaxelCloudBucketMountEntry,
  isBlaxelDriveMountEntry,
  mountBlaxelCloudBucket,
  mountBlaxelDrive,
  unmountBlaxelDrive,
  unmountBlaxelFuseMount,
  type BlaxelDriveApi,
} from './mounts';
import type { RemoteMountCommand } from '../shared/inContainerMounts';

export const DEFAULT_BLAXEL_WORKSPACE_ROOT = '/workspace';
const BLAXEL_AUTOGENERATED_NAME_CREATE_ATTEMPTS = 5;
const BLAXEL_NON_RESUMABLE_SANDBOX_STATUSES = new Set([
  'DEACTIVATING',
  'DEACTIVATED',
  'DELETING',
  'FAILED',
  'TERMINATING',
  'TERMINATED',
]);

type BlaxelCreateInternalOptions = {
  allowExistingNamedSandbox?: boolean;
};

type BlaxelSandboxClass = {
  create(params: Record<string, unknown>): Promise<BlaxelSandboxLike>;
  get(name: string): Promise<BlaxelSandboxLike>;
};

type BlaxelSandboxLike = {
  name?: string;
  metadata?: {
    name?: string;
    createdAt?: string;
    workspace?: string;
    createdBy?: string;
  };
  status?: string;
  url?: string;
  sandbox?: {
    metadata?: {
      url?: string;
    };
  };
  process: {
    exec(params: Record<string, unknown>): Promise<BlaxelProcessResult>;
  };
  fs: {
    mkdir(path: string): Promise<void>;
    write(path: string, content: string): Promise<void>;
    writeBinary(path: string, content: Uint8Array): Promise<void>;
    read(path: string): Promise<string>;
    readBinary(path: string): Promise<Blob | Uint8Array | ArrayBuffer>;
    rm(path: string, recursive?: boolean): Promise<void>;
  };
  previews?: BlaxelPreviewApi;
  drives?: BlaxelDriveApi;
  delete(): Promise<void>;
};

type BlaxelPreviewApi = {
  createIfNotExists(params: Record<string, unknown>): Promise<unknown>;
};

type BlaxelProcessResult = {
  stdout?: string;
  stderr?: string;
  exitCode?: number | null;
};

export interface BlaxelSandboxTimeouts {
  execTimeoutMs?: number;
  createTimeoutMs?: number;
  cleanupTimeoutMs?: number;
  fileUploadTimeoutMs?: number;
  fileDownloadTimeoutMs?: number;
  workspaceTarTimeoutMs?: number;
  fastOperationTimeoutMs?: number;
}

export interface BlaxelSandboxClientOptions extends SandboxClientOptions {
  image?: string;
  memory?: number;
  region?: string;
  ports?: Array<Record<string, unknown>>;
  exposedPortPublic?: boolean;
  exposedPortUrlTtlS?: number;
  timeoutMs?: number;
  createTimeoutMs?: number;
  timeouts?: BlaxelSandboxTimeouts;
  apiKey?: string;
  env?: Record<string, string>;
  labels?: Record<string, string>;
  ttl?: string;
  name?: string;
  pauseOnExit?: boolean;
  archiveLimits?: SandboxArchiveLimits | null;
}

export interface BlaxelSandboxSessionState extends SandboxSessionState {
  sandboxName: string;
  sandboxIdentity?: string;
  mountArtifactScope?: string;
  image?: string;
  memory?: number;
  region?: string;
  ports?: Array<Record<string, unknown>>;
  exposedPortPublic?: boolean;
  exposedPortUrlTtlS?: number;
  timeoutMs?: number;
  createTimeoutMs?: number;
  timeouts?: BlaxelSandboxTimeouts;
  sandboxUrl?: string;
  labels?: Record<string, string>;
  ttl?: string;
  pauseOnExit: boolean;
  ownsSandbox: boolean;
  environment: Record<string, string>;
}

export class BlaxelSandboxSession extends RemoteSandboxSessionBase<BlaxelSandboxSessionState> {
  private readonly sandbox: BlaxelSandboxLike;
  private readonly apiKey?: string;
  private ownsSandbox: boolean;
  private closed = false;
  private readonly ptyProcesses = new PtyProcessRegistry();
  private readonly activeFuseMountPaths = new Set<string>();
  private readonly activeDriveMountPaths = new Set<string>();

  constructor(args: {
    state: BlaxelSandboxSessionState;
    sandbox: BlaxelSandboxLike;
    apiKey?: string;
    ownsSandbox?: boolean;
    concurrencyLimits?: SandboxConcurrencyLimits;
    archiveLimits?: SandboxArchiveLimits | null;
  }) {
    super({
      state: args.state,
      options: {
        providerName: 'BlaxelSandboxClient',
        providerId: 'blaxel',
        concurrencyLimits: args.concurrencyLimits,
        archiveLimits: args.archiveLimits,
      },
    });
    this.sandbox = args.sandbox;
    this.apiKey = args.apiKey;
    this.ownsSandbox = args.ownsSandbox ?? true;
    this.ensureMountArtifactScope();
  }

  override supportsPty(): boolean {
    return Boolean(this.state.sandboxUrl && this.apiKey);
  }

  async writeStdin(args: WriteStdinArgs): Promise<string> {
    return await writePtyStdin({
      providerName: 'BlaxelSandboxClient',
      registry: this.ptyProcesses,
      sessionId: args.sessionId,
      chars: args.chars,
      yieldTimeMs: args.yieldTimeMs,
      maxOutputTokens: args.maxOutputTokens,
    });
  }

  protected override async execPtyCommand(
    args: ExecCommandArgs,
  ): Promise<string> {
    assertRunAsUnsupported('BlaxelSandboxClient', args.runAs);
    if (!this.state.sandboxUrl || !this.apiKey) {
      throw new SandboxUnsupportedFeatureError(
        'BlaxelSandboxClient tty=true requires a sandbox URL and apiKey.',
        {
          provider: 'blaxel',
          feature: 'tty',
        },
      );
    }

    const start = Date.now();
    const entry = createPtyProcessEntry({ tty: true });
    const socket = await openPtyWebSocket({
      url: buildBlaxelPtyWebSocketUrl({
        sandboxUrl: this.state.sandboxUrl,
        token: this.apiKey,
        sessionId: `pty-${Math.random().toString(16).slice(2, 14)}`,
        cwd: resolveSandboxWorkdir(this.state.manifest.root, args.workdir),
      }),
      providerName: 'BlaxelSandboxClient',
    });
    const removeMessageListener = addPtyWebSocketListener(
      socket,
      'message',
      (event) => handleBlaxelPtyMessage(entry, event),
    );
    const removeCloseListener = addPtyWebSocketListener(
      socket,
      'close',
      (event) => {
        markPtyDone(entry, blaxelPtyCloseExitCode(entry, event));
      },
    );
    const removeErrorListener = addPtyWebSocketListener(socket, 'error', () => {
      markPtyDone(entry, 1);
    });
    entry.sendInput = async (chars) => {
      socket.send(JSON.stringify({ type: 'input', data: chars }));
    };
    entry.terminate = async () => {
      removeMessageListener();
      removeCloseListener();
      removeErrorListener();
      socket.close();
    };
    let registered = false;
    try {
      await entry.sendInput(
        `${shellCommandForPty({
          ...args,
          cmd: buildShellCommand(args.cmd, this.state.environment),
        })}\n`,
      );

      const { sessionId, pruned } = this.ptyProcesses.register(entry);
      registered = true;
      if (pruned) {
        await pruned.terminate?.().catch(() => {});
      }

      return await formatPtyExecUpdate({
        registry: this.ptyProcesses,
        sessionId,
        entry,
        startTime: start,
        yieldTimeMs: args.yieldTimeMs,
        maxOutputTokens: args.maxOutputTokens,
      });
    } finally {
      if (!registered) {
        await entry.terminate?.().catch(() => {});
      }
    }
  }

  protected override allowOnDemandExposedPorts(): boolean {
    return true;
  }

  protected override useCachedExposedPortEndpoint(_port: number): boolean {
    return this.state.exposedPortPublic !== false;
  }

  protected override exposedPortSource(): string {
    return 'preview URL';
  }

  protected override async resolveRemoteExposedPort(
    requestedPort: number,
  ): Promise<ExposedPortEndpoint> {
    if (!this.sandbox.previews?.createIfNotExists) {
      throw new SandboxProviderError(
        'BlaxelSandboxClient exposed port resolution requires the Blaxel previews API.',
        {
          provider: 'blaxel',
          port: requestedPort,
        },
      );
    }

    let preview: unknown;
    try {
      preview = await this.sandbox.previews.createIfNotExists({
        metadata: { name: `port-${requestedPort}` },
        spec: {
          port: requestedPort,
          public: this.state.exposedPortPublic ?? true,
        },
      });
    } catch (error) {
      throw new SandboxProviderError(
        `BlaxelSandboxClient failed to create a preview for exposed port ${requestedPort}.`,
        {
          provider: 'blaxel',
          port: requestedPort,
          cause: providerErrorMessage(error),
        },
      );
    }

    const url = extractBlaxelPreviewUrl(preview);
    if (!url) {
      throw new SandboxProviderError(
        'BlaxelSandboxClient preview did not include a URL.',
        {
          provider: 'blaxel',
          port: requestedPort,
        },
      );
    }

    const query =
      this.state.exposedPortPublic === false
        ? await createBlaxelPreviewTokenQuery(
            preview,
            this.state.exposedPortUrlTtlS ?? 3600,
            requestedPort,
          )
        : undefined;

    return parseExposedPortEndpoint(url, {
      providerName: 'BlaxelSandboxClient',
      source: 'preview URL',
      query,
    });
  }

  async prepareWorkspaceRoot(): Promise<void> {
    const result = await this.sandbox.process.exec({
      command: `mkdir -p -- ${shellQuote(this.state.manifest.root)}`,
      workingDir: '/',
      waitForCompletion: true,
      timeout: toBlaxelTimeoutSeconds(
        this.state.timeouts?.fastOperationTimeoutMs,
      ),
    });
    if ((result.exitCode ?? 1) !== 0) {
      throw new SandboxProviderError(
        'BlaxelSandboxClient failed to prepare the workspace root.',
        {
          provider: 'blaxel',
          operation: 'prepare workspace root',
          sandboxName: this.state.sandboxName,
          root: this.state.manifest.root,
          stderr: result.stderr ?? '',
          stdout: result.stdout ?? '',
        },
      );
    }
  }

  async close(): Promise<void> {
    await this.ptyProcesses.terminateAll();
    if (this.state.pauseOnExit || this.closed) {
      return;
    }

    await withSandboxSpan(
      'sandbox.shutdown',
      {
        backend_id: 'blaxel',
        sandbox_name: this.state.sandboxName,
      },
      async () => {
        await this.unmountActiveMounts();
        if (this.ownsSandbox) {
          await this.sandbox.delete();
        }
      },
    );
    this.closed = true;
  }

  async shutdown(_options?: SandboxSessionLifecycleOptions): Promise<void> {
    await this.close();
  }

  async delete(options?: SandboxSessionLifecycleOptions): Promise<void> {
    await this.ptyProcesses.terminateAll();
    if (this.closed) {
      return;
    }
    if (this.shouldPreserveOnCleanup(options)) {
      this.closed = true;
      return;
    }
    await withSandboxSpan(
      'sandbox.shutdown',
      {
        backend_id: 'blaxel',
        sandbox_name: this.state.sandboxName,
      },
      async () => {
        await this.unmountActiveMounts();
        if (this.ownsSandbox) {
          await this.sandbox.delete();
        }
      },
    );
    this.closed = true;
  }

  private shouldPreserveOnCleanup(
    options?: SandboxSessionLifecycleOptions,
  ): boolean {
    return (
      options?.reason === 'cleanup' &&
      options.preserveOwnedSessions === true &&
      this.state.pauseOnExit &&
      this.ownsSandbox
    );
  }

  async rehydrateActiveMountPathsFromManifest(): Promise<void> {
    for (const {
      logicalPath,
      entry,
    } of this.state.manifest.mountTargetsForMaterialization()) {
      const mountPath = await this.resolveRemotePath(
        entry.mountPath ?? logicalPath,
        { forWrite: true },
      );
      if (isBlaxelCloudBucketMountEntry(entry)) {
        this.activeFuseMountPaths.add(mountPath);
      } else if (isBlaxelDriveMountEntry(entry)) {
        this.activeDriveMountPaths.add(mountPath);
      }
    }
  }

  protected override manifestMetadataSupport() {
    return SANDBOX_MANIFEST_METADATA_SUPPORT;
  }

  protected override manifestMaterializationOptions() {
    return {
      materializeMount: this.materializeMountEntry.bind(this),
    };
  }

  protected override assertExecRunAs(_runAs?: string): void {
    void _runAs;
  }

  protected override assertFilesystemRunAs(_runAs?: string): void {
    void _runAs;
  }

  private async materializeMountEntry(
    absolutePath: string,
    entry: Mount | TypedMount,
  ): Promise<void> {
    const mountPath = await this.resolveRemotePath(
      entry.mountPath ?? absolutePath,
      { forWrite: true },
    );
    if (entry.mountStrategy?.type === 'blaxel_cloud_bucket') {
      await mountBlaxelCloudBucket({
        entry,
        mountPath,
        artifactScope: this.ensureMountArtifactScope(),
        runCommand: this.mountCommandRunner(),
        writeSecretFile: this.writeMountSecretFile.bind(this),
      });
      this.activeFuseMountPaths.add(mountPath);
      return;
    }
    if (entry.mountStrategy?.type === 'blaxel_drive') {
      const config = await mountBlaxelDrive({
        entry,
        mountPath,
        drives: this.sandbox.drives,
      });
      this.activeDriveMountPaths.add(config.mountPath);
      return;
    }
    throw new SandboxUnsupportedFeatureError(
      'BlaxelSandboxClient only supports BlaxelCloudBucketMountStrategy and BlaxelDriveMountStrategy mount entries.',
      {
        provider: 'blaxel',
        feature: 'entry.mountStrategy',
        path: absolutePath,
        mountType: entry.type,
        strategyType: entry.mountStrategy?.type,
      },
    );
  }

  private async unmountActiveMounts(): Promise<void> {
    for (const mountPath of [...this.activeDriveMountPaths].reverse()) {
      try {
        await unmountBlaxelDrive({
          mountPath,
          drives: this.sandbox.drives,
        });
        this.activeDriveMountPaths.delete(mountPath);
      } catch (error) {
        throw new SandboxProviderError(
          'BlaxelSandboxClient failed to unmount an active drive mount.',
          {
            provider: 'blaxel',
            mountPath,
            cause: providerErrorMessage(error),
          },
        );
      }
    }
    for (const mountPath of [...this.activeFuseMountPaths].reverse()) {
      try {
        await unmountBlaxelFuseMount({
          mountPath,
          artifactScope: this.ensureMountArtifactScope(),
          runCommand: this.mountCommandRunner(),
        });
        this.activeFuseMountPaths.delete(mountPath);
      } catch (error) {
        throw new SandboxProviderError(
          'BlaxelSandboxClient failed to unmount an active FUSE mount.',
          {
            provider: 'blaxel',
            mountPath,
            cause: providerErrorMessage(error),
          },
        );
      }
    }
  }

  private mountCommandRunner(): RemoteMountCommand {
    return async (command, options = {}) => {
      const result = await this.sandbox.process.exec({
        command,
        workingDir: '/',
        waitForCompletion: true,
        timeout: toBlaxelTimeoutSeconds(
          options.timeoutMs ??
            this.state.timeouts?.fastOperationTimeoutMs ??
            this.state.timeoutMs,
        ),
      });
      return {
        status: result.exitCode ?? 1,
        stdout: result.stdout ?? '',
        stderr: result.stderr ?? '',
      };
    };
  }

  private async writeMountSecretFile(
    path: string,
    content: string,
  ): Promise<void> {
    const operation = this.sandbox.fs.write(path, content);
    await withBlaxelOperationTimeout(
      operation,
      this.state.timeouts?.fileUploadTimeoutMs,
      'write mount secret',
      {
        onTimeout: () => {
          void operation.then(
            async () => {
              await this.sandbox.fs.rm(path).catch(() => {});
            },
            () => {},
          );
        },
      },
    );
  }

  protected override async runRemoteCommand(
    command: string,
    options: RemoteSandboxCommandOptions,
  ): Promise<RemoteSandboxCommandResult> {
    const shellCommand = buildShellCommand(command, this.state.environment);
    const commandForUser = options.runAs
      ? `sudo -n -u ${shellQuote(options.runAs)} -- sh -lc ${shellQuote(shellCommand)}`
      : shellCommand;
    const result = await this.sandbox.process.exec({
      command: commandForUser,
      workingDir: options.workdir,
      waitForCompletion: true,
      timeout: toBlaxelTimeoutSeconds(this.timeoutForCommand(options)),
    });
    return {
      status: result.exitCode ?? 1,
      stdout: result.stdout ?? '',
      stderr: result.stderr ?? '',
    };
  }

  protected override async mkdirRemote(path: string): Promise<void> {
    await this.sandbox.fs.mkdir(path);
  }

  protected override async readRemoteText(path: string): Promise<string> {
    try {
      return await withBlaxelOperationTimeout(
        this.sandbox.fs.read(path),
        this.state.timeouts?.fileDownloadTimeoutMs,
        'read file',
      );
    } catch (error) {
      throw blaxelReadError(path, error);
    }
  }

  protected override async readRemoteFile(path: string): Promise<Uint8Array> {
    try {
      return await toUint8Array(
        await withBlaxelOperationTimeout(
          this.sandbox.fs.readBinary(path),
          this.state.timeouts?.fileDownloadTimeoutMs,
          'read binary file',
        ),
      );
    } catch (error) {
      throw blaxelReadError(path, error);
    }
  }

  protected override async writeRemoteFile(
    path: string,
    content: string | Uint8Array,
  ): Promise<void> {
    const tempPath = remoteWriteTempPath(path);
    if (typeof content === 'string') {
      await this.writeRemoteTempFile(
        tempPath,
        this.sandbox.fs.write(tempPath, content),
        'write file',
      );
    } else {
      await this.writeRemoteTempFile(
        tempPath,
        this.sandbox.fs.writeBinary(tempPath, content),
        'write binary file',
      );
    }
    try {
      const result = await this.sandbox.process.exec({
        command: `mv -f -- ${shellQuote(tempPath)} ${shellQuote(path)}`,
        workingDir: '/',
        waitForCompletion: true,
        timeout: toBlaxelTimeoutSeconds(
          this.state.timeouts?.fileUploadTimeoutMs,
        ),
      });
      if ((result.exitCode ?? 1) === 0) {
        return;
      }
      throw new SandboxProviderError(
        'BlaxelSandboxClient failed to commit uploaded file.',
        {
          provider: 'blaxel',
          operation: 'commit uploaded file',
          path,
          tempPath,
          exitCode: result.exitCode ?? 1,
          stdout: result.stdout ?? '',
          stderr: result.stderr ?? '',
        },
      );
    } catch (error) {
      await this.sandbox.fs.rm(tempPath).catch(() => {});
      throw error;
    }
  }

  private async writeRemoteTempFile(
    tempPath: string,
    operation: Promise<unknown>,
    operationName: string,
  ): Promise<void> {
    await withBlaxelOperationTimeout(
      operation,
      this.state.timeouts?.fileUploadTimeoutMs,
      operationName,
      {
        onTimeout: () => {
          void operation.then(
            async () => {
              await this.sandbox.fs.rm(tempPath).catch(() => {});
            },
            () => {},
          );
        },
      },
    );
  }

  protected override async deleteRemotePath(path: string): Promise<void> {
    await this.sandbox.fs.rm(path);
  }

  private ensureMountArtifactScope(): string {
    this.state.mountArtifactScope ??= randomUUID();
    return this.state.mountArtifactScope;
  }

  private timeoutForCommand(options: RemoteSandboxCommandOptions) {
    if (options.timeoutMs !== undefined) {
      return options.timeoutMs;
    }
    if (options.kind === 'archive') {
      return this.state.timeouts?.workspaceTarTimeoutMs ?? this.state.timeoutMs;
    }
    if (options.kind === 'exec') {
      return this.state.timeouts?.execTimeoutMs ?? this.state.timeoutMs;
    }
    if (options.kind === 'path' || options.kind === 'running') {
      return this.state.timeouts?.fastOperationTimeoutMs;
    }
    return undefined;
  }
}

/**
 * @see {@link https://docs.blaxel.ai/Sandboxes/Overview | Sandboxes overview}.
 * @see {@link https://docs.blaxel.ai/Sandboxes/Filesystem | Filesystem operations}.
 * @see {@link https://docs.blaxel.ai/Sandboxes/Sessions | Client-side sessions}.
 */
export class BlaxelSandboxClient implements SandboxClient<
  BlaxelSandboxClientOptions,
  BlaxelSandboxSessionState
> {
  readonly backendId = 'blaxel';
  private readonly options: BlaxelSandboxClientOptions;

  constructor(options: BlaxelSandboxClientOptions = {}) {
    this.options = options;
  }

  async create(
    args?: SandboxClientCreateArgs<BlaxelSandboxClientOptions> | Manifest,
    manifestOptions?: BlaxelSandboxClientOptions,
    internalOptions: BlaxelCreateInternalOptions = {},
  ): Promise<BlaxelSandboxSession> {
    const createArgs = normalizeSandboxClientCreateArgs(args, manifestOptions);
    assertCoreSnapshotUnsupported('BlaxelSandboxClient', createArgs.snapshot);
    const manifest = createArgs.manifest;
    const resolvedOptions = {
      ...this.options,
      ...createArgs.options,
    };
    const timeouts = resolveBlaxelTimeouts(resolvedOptions);
    assertSandboxManifestMetadataSupported(
      'BlaxelSandboxClient',
      manifest,
      SANDBOX_MANIFEST_METADATA_SUPPORT,
    );
    const SandboxInstance = await loadBlaxelSandboxClass();

    return await withSandboxSpan(
      'sandbox.start',
      {
        backend_id: this.backendId,
      },
      async () => {
        const sandboxCreateParams = {
          ...(resolvedOptions.image ? { image: resolvedOptions.image } : {}),
          ...(typeof resolvedOptions.memory === 'number'
            ? { memory: resolvedOptions.memory }
            : {}),
          ...(resolvedOptions.region ? { region: resolvedOptions.region } : {}),
          ...(resolvedOptions.ports ? { ports: resolvedOptions.ports } : {}),
          ...(typeof resolvedOptions.exposedPortPublic === 'boolean'
            ? { exposedPortPublic: resolvedOptions.exposedPortPublic }
            : {}),
          ...(typeof resolvedOptions.exposedPortUrlTtlS === 'number'
            ? { exposedPortUrlTtlS: resolvedOptions.exposedPortUrlTtlS }
            : {}),
          ...(typeof resolvedOptions.timeoutMs === 'number'
            ? { timeoutMs: resolvedOptions.timeoutMs }
            : {}),
          ...(typeof timeouts.createTimeoutMs === 'number'
            ? { createTimeoutMs: timeouts.createTimeoutMs }
            : {}),
          ...(resolvedOptions.labels ? { labels: resolvedOptions.labels } : {}),
          ...(resolvedOptions.ttl ? { ttl: resolvedOptions.ttl } : {}),
        };
        const { sandbox, ownsSandbox, sandboxName } = await withProviderError(
          'BlaxelSandboxClient',
          'blaxel',
          'create sandbox',
          async () =>
            await createBlaxelSandboxWithOwnership({
              SandboxInstance,
              sandboxName: resolvedOptions.name,
              allowExistingNamedSandbox:
                internalOptions.allowExistingNamedSandbox ?? true,
              paramsForName: (sandboxName) => ({
                name: sandboxName,
                ...sandboxCreateParams,
              }),
            }),
          { sandboxName: resolvedOptions.name },
        );

        let environment: Record<string, string>;
        try {
          environment = await materializeEnvironment(
            manifest,
            resolvedOptions.env,
          );
        } catch (error) {
          if (ownsSandbox) {
            try {
              await sandbox.delete();
            } catch (deleteError) {
              throw new UserError(
                `Failed to materialize a Blaxel sandbox environment and delete the sandbox. Environment error: ${providerErrorMessage(error)} Delete error: ${providerErrorMessage(deleteError)}`,
              );
            }
          }
          throw error;
        }

        let sandboxForIdentity = sandbox;
        if (ownsSandbox && (resolvedOptions.pauseOnExit ?? false)) {
          try {
            sandboxForIdentity = await canonicalizeBlaxelSandboxIdentitySource({
              SandboxInstance,
              sandboxName,
            });
          } catch (error) {
            try {
              await sandbox.delete();
            } catch (deleteError) {
              throw new UserError(
                `Failed to verify a Blaxel sandbox identity and delete the sandbox. Identity error: ${providerErrorMessage(error)} Delete error: ${providerErrorMessage(deleteError)}`,
              );
            }
            throw error;
          }
        }
        const sandboxUrl =
          extractBlaxelSandboxUrl(sandboxForIdentity) ??
          extractBlaxelSandboxUrl(sandbox);

        const session = new BlaxelSandboxSession({
          sandbox,
          apiKey: resolvedOptions.apiKey ?? loadEnv().BL_API_KEY,
          ownsSandbox,
          concurrencyLimits: createArgs.concurrencyLimits,
          archiveLimits: createArgs.archiveLimits,
          state: {
            manifest,
            sandboxName,
            image: resolvedOptions.image,
            memory: resolvedOptions.memory,
            region: resolvedOptions.region,
            ports: resolvedOptions.ports,
            exposedPortPublic: resolvedOptions.exposedPortPublic,
            exposedPortUrlTtlS: resolvedOptions.exposedPortUrlTtlS,
            timeoutMs: resolvedOptions.timeoutMs,
            createTimeoutMs: timeouts.createTimeoutMs,
            timeouts,
            sandboxUrl,
            sandboxIdentity: extractBlaxelSandboxIdentity(sandboxForIdentity),
            mountArtifactScope: randomUUID(),
            labels: resolvedOptions.labels,
            ttl: resolvedOptions.ttl,
            pauseOnExit: resolvedOptions.pauseOnExit ?? false,
            ownsSandbox,
            environment,
          },
        });

        try {
          await session.prepareWorkspaceRoot();
          await session.applyManifest(manifest);
        } catch (error) {
          session.state.pauseOnExit = false;
          await closeRemoteSessionOnManifestError('Blaxel', session, error);
        }
        return session;
      },
    );
  }

  async serializeSessionState(
    state: BlaxelSandboxSessionState,
  ): Promise<Record<string, unknown>> {
    return serializeRemoteSandboxSessionState(state);
  }

  canPersistOwnedSessionState(state: BlaxelSandboxSessionState): boolean {
    return state.pauseOnExit && state.ownsSandbox && !!state.sandboxIdentity;
  }

  async deserializeSessionState(
    state: Record<string, unknown>,
  ): Promise<BlaxelSandboxSessionState> {
    const baseState = deserializeRemoteSandboxSessionStateValues(
      state,
      this.options.env,
    );
    return {
      ...state,
      ...baseState,
      sandboxName: readString(state, 'sandboxName'),
      image: readOptionalString(state, 'image'),
      memory: readOptionalNumber(state, 'memory'),
      region: readOptionalString(state, 'region'),
      ports: readOptionalRecordArray(state.ports),
      exposedPortPublic: readOptionalBoolean(state, 'exposedPortPublic'),
      exposedPortUrlTtlS: readOptionalNumber(state, 'exposedPortUrlTtlS'),
      timeoutMs: readOptionalNumber(state, 'timeoutMs'),
      createTimeoutMs: readOptionalNumber(state, 'createTimeoutMs'),
      timeouts: resolveBlaxelTimeouts({
        timeoutMs: readOptionalNumber(state, 'timeoutMs'),
        createTimeoutMs: readOptionalNumber(state, 'createTimeoutMs'),
        timeouts: isRecord(state.timeouts)
          ? (state.timeouts as BlaxelSandboxTimeouts)
          : undefined,
      }),
      sandboxUrl: readOptionalString(state, 'sandboxUrl'),
      sandboxIdentity: readOptionalString(state, 'sandboxIdentity'),
      mountArtifactScope:
        readOptionalString(state, 'mountArtifactScope') ?? randomUUID(),
      labels: readOptionalStringRecord(state.labels),
      ttl: readOptionalString(state, 'ttl'),
      pauseOnExit: Boolean(state.pauseOnExit),
      ownsSandbox: readOptionalBoolean(state, 'ownsSandbox') ?? true,
    };
  }

  async resume(
    state: BlaxelSandboxSessionState,
  ): Promise<BlaxelSandboxSession> {
    const SandboxInstance = await loadBlaxelSandboxClass();
    let sandbox: BlaxelSandboxLike;
    try {
      sandbox = await SandboxInstance.get(state.sandboxName);
    } catch (error) {
      assertResumeRecreateAllowed(error, {
        providerName: 'BlaxelSandboxClient',
        provider: 'blaxel',
        details: { sandboxName: state.sandboxName },
      });
      return await this.recreateFromState(state);
    }

    if (isBlaxelSandboxNonResumable(sandbox)) {
      return await this.recreateFromState(state);
    }

    if (state.ownsSandbox) {
      assertBlaxelSandboxIdentityMatchesState(sandbox, state);
    }

    const sandboxUrl = extractBlaxelSandboxUrl(sandbox);
    if (sandboxUrl) {
      state.sandboxUrl = sandboxUrl;
    }
    const session = new BlaxelSandboxSession({
      state,
      sandbox,
      apiKey: this.options.apiKey ?? loadEnv().BL_API_KEY,
      ownsSandbox: state.ownsSandbox,
      archiveLimits: this.options.archiveLimits,
    });
    await session.rehydrateActiveMountPathsFromManifest();
    return session;
  }

  private async recreateFromState(
    state: BlaxelSandboxSessionState,
  ): Promise<BlaxelSandboxSession> {
    const session = await this.create(
      state.manifest,
      {
        image: state.image,
        memory: state.memory,
        region: state.region,
        ports: state.ports,
        exposedPortPublic: state.exposedPortPublic,
        exposedPortUrlTtlS: state.exposedPortUrlTtlS,
        timeoutMs: state.timeoutMs,
        createTimeoutMs: state.createTimeoutMs,
        timeouts: state.timeouts,
        apiKey: this.options.apiKey,
        labels: state.labels,
        ttl: state.ttl,
        name: state.sandboxName,
        pauseOnExit: state.pauseOnExit,
        env: state.environment,
      },
      {
        allowExistingNamedSandbox: !state.ownsSandbox,
      },
    );
    return session;
  }
}

async function loadBlaxelSandboxClass(): Promise<BlaxelSandboxClass> {
  try {
    const { SandboxInstance } = await import('@blaxel/core');
    if (!SandboxInstance) {
      throw new Error('Missing SandboxInstance export from @blaxel/core.');
    }
    return adaptBlaxelSandboxClass(SandboxInstance);
  } catch (error) {
    throw new UserError(
      `Blaxel sandbox support requires the optional \`@blaxel/core\` package. Install it before using Blaxel-backed sandbox examples. ${(error as Error).message}`,
    );
  }
}

async function createBlaxelSandboxWithOwnership(args: {
  SandboxInstance: BlaxelSandboxClass;
  sandboxName?: string;
  allowExistingNamedSandbox: boolean;
  paramsForName: (sandboxName: string) => Record<string, unknown>;
}): Promise<{
  sandbox: BlaxelSandboxLike;
  ownsSandbox: boolean;
  sandboxName: string;
}> {
  if (!args.sandboxName) {
    return await createAutogeneratedBlaxelSandbox(args);
  }

  return await createNamedBlaxelSandboxWithOwnership({
    SandboxInstance: args.SandboxInstance,
    sandboxName: args.sandboxName,
    allowExistingNamedSandbox: args.allowExistingNamedSandbox,
    params: args.paramsForName(args.sandboxName),
  });
}

async function createNamedBlaxelSandboxWithOwnership(args: {
  SandboxInstance: BlaxelSandboxClass;
  sandboxName: string;
  allowExistingNamedSandbox: boolean;
  params: Record<string, unknown>;
}): Promise<{
  sandbox: BlaxelSandboxLike;
  ownsSandbox: boolean;
  sandboxName: string;
}> {
  try {
    return {
      sandbox: await args.SandboxInstance.create(args.params),
      ownsSandbox: true,
      sandboxName: args.sandboxName,
    };
  } catch (error) {
    if (!isBlaxelSandboxAlreadyExistsError(error)) {
      throw error;
    }
    if (!args.allowExistingNamedSandbox) {
      throw new UserError(
        `Blaxel sandbox ${args.sandboxName} cannot be safely recreated because another sandbox already uses that name.`,
      );
    }
  }

  const existing = await args.SandboxInstance.get(args.sandboxName);
  if (!isBlaxelSandboxNonResumable(existing)) {
    return {
      sandbox: existing,
      ownsSandbox: false,
      sandboxName: args.sandboxName,
    };
  }

  try {
    return {
      sandbox: await args.SandboxInstance.create(args.params),
      ownsSandbox: true,
      sandboxName: args.sandboxName,
    };
  } catch (error) {
    if (!isBlaxelSandboxAlreadyExistsError(error)) {
      throw error;
    }
    if (!args.allowExistingNamedSandbox) {
      throw new UserError(
        `Blaxel sandbox ${args.sandboxName} cannot be safely recreated because another sandbox already uses that name.`,
      );
    }
    const fallback = await args.SandboxInstance.get(args.sandboxName);
    assertBlaxelSandboxReusable(fallback, args.sandboxName);
    return {
      sandbox: fallback,
      ownsSandbox: false,
      sandboxName: args.sandboxName,
    };
  }
}

async function createAutogeneratedBlaxelSandbox(args: {
  SandboxInstance: BlaxelSandboxClass;
  paramsForName: (sandboxName: string) => Record<string, unknown>;
}): Promise<{
  sandbox: BlaxelSandboxLike;
  ownsSandbox: boolean;
  sandboxName: string;
}> {
  let lastConflict: unknown;
  for (
    let attempt = 0;
    attempt < BLAXEL_AUTOGENERATED_NAME_CREATE_ATTEMPTS;
    attempt += 1
  ) {
    const sandboxName = generateBlaxelSandboxName();
    try {
      return {
        sandbox: await args.SandboxInstance.create(
          args.paramsForName(sandboxName),
        ),
        ownsSandbox: true,
        sandboxName,
      };
    } catch (error) {
      if (!isBlaxelSandboxAlreadyExistsError(error)) {
        throw error;
      }
      lastConflict = error;
    }
  }
  throw lastConflict;
}

async function canonicalizeBlaxelSandboxIdentitySource(args: {
  SandboxInstance: BlaxelSandboxClass;
  sandboxName: string;
}): Promise<BlaxelSandboxLike> {
  try {
    return await args.SandboxInstance.get(args.sandboxName);
  } catch (error) {
    throw new UserError(
      `Blaxel sandbox ${args.sandboxName} cannot be safely preserved because its identity could not be verified after create. ${providerErrorMessage(error)}`,
    );
  }
}

function generateBlaxelSandboxName(): string {
  return `openai-agents-${Math.random().toString(16).slice(2, 10)}`;
}

function isBlaxelSandboxNonResumable(sandbox: BlaxelSandboxLike): boolean {
  const status = sandbox.status?.trim().toUpperCase();
  return status ? BLAXEL_NON_RESUMABLE_SANDBOX_STATUSES.has(status) : false;
}

function assertBlaxelSandboxReusable(
  sandbox: BlaxelSandboxLike,
  sandboxName: string,
): void {
  if (!isBlaxelSandboxNonResumable(sandbox)) {
    return;
  }
  throw new UserError(
    `Blaxel sandbox ${sandboxName} cannot be safely reused because its status is ${sandbox.status ?? 'unknown'}.`,
  );
}

function assertBlaxelSandboxIdentityMatchesState(
  sandbox: BlaxelSandboxLike,
  state: BlaxelSandboxSessionState,
): void {
  const identity = extractBlaxelSandboxIdentity(sandbox);
  if (identity && identity === state.sandboxIdentity) {
    return;
  }
  throw new UserError(
    `Blaxel sandbox ${state.sandboxName} cannot be safely resumed with ownership because its identity could not be verified.`,
  );
}

function extractBlaxelSandboxIdentity(
  sandbox: BlaxelSandboxLike,
): string | undefined {
  const metadata = sandbox.metadata;
  if (!isRecord(metadata)) {
    return undefined;
  }
  const name = readMetadataString(metadata, 'name');
  const createdAt = readMetadataString(metadata, 'createdAt');
  if (!name || !createdAt) {
    return undefined;
  }
  return JSON.stringify({
    name,
    createdAt,
    workspace: readMetadataString(metadata, 'workspace') ?? null,
    createdBy: readMetadataString(metadata, 'createdBy') ?? null,
  });
}

function readMetadataString(
  metadata: Record<string, unknown>,
  key: string,
): string | undefined {
  const value = metadata[key];
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function isBlaxelSandboxAlreadyExistsError(error: unknown): boolean {
  if (isRecord(error)) {
    if (isConflictValue(error.code)) {
      return true;
    }
    const response = error.response;
    if (isRecord(response) && isConflictValue(response.status)) {
      return true;
    }
  }
  return /\b(409|already exists|SANDBOX_ALREADY_EXISTS)\b/iu.test(
    providerErrorMessage(error),
  );
}

function isConflictValue(value: unknown): boolean {
  if (value === 409 || value === '409') {
    return true;
  }
  return (
    typeof value === 'string' &&
    value.trim().toUpperCase() === 'SANDBOX_ALREADY_EXISTS'
  );
}

function adaptBlaxelSandboxClass(
  SandboxInstance: typeof import('@blaxel/core').SandboxInstance,
): BlaxelSandboxClass {
  return {
    create: async (params) =>
      adaptBlaxelSandbox(
        await SandboxInstance.create(
          params as Parameters<typeof SandboxInstance.create>[0],
        ),
      ),
    get: async (name) => adaptBlaxelSandbox(await SandboxInstance.get(name)),
  };
}

function adaptBlaxelSandbox(
  sandbox: import('@blaxel/core').SandboxInstance,
): BlaxelSandboxLike {
  const sandboxUrl = extractBlaxelSandboxUrl(sandbox);
  const previews = adaptBlaxelPreviewApi(
    (sandbox as { previews?: unknown }).previews,
  );
  return {
    metadata: sandbox.metadata,
    url: sandboxUrl,
    status: typeof sandbox.status === 'string' ? sandbox.status : undefined,
    ...(sandboxUrl ? { sandbox: { metadata: { url: sandboxUrl } } } : {}),
    process: {
      exec: async (params) =>
        await sandbox.process.exec(
          params as Parameters<typeof sandbox.process.exec>[0],
        ),
    },
    fs: {
      mkdir: async (path) => {
        await sandbox.fs.mkdir(path);
      },
      write: async (path, content) => {
        await sandbox.fs.write(path, content);
      },
      writeBinary: async (path, content) => {
        await sandbox.fs.writeBinary(path, content);
      },
      read: async (path) => await sandbox.fs.read(path),
      readBinary: async (path) => await sandbox.fs.readBinary(path),
      rm: async (path, recursive) => {
        await sandbox.fs.rm(path, recursive);
      },
    },
    ...(previews ? { previews } : {}),
    drives: adaptBlaxelDriveApi(sandbox.drives),
    delete: async () => {
      await sandbox.delete();
    },
  };
}

function adaptBlaxelPreviewApi(
  previews: unknown,
): BlaxelPreviewApi | undefined {
  if (!isRecord(previews)) {
    return undefined;
  }
  const createIfNotExists = previews.createIfNotExists;
  if (typeof createIfNotExists !== 'function') {
    return undefined;
  }
  return {
    createIfNotExists: async (params) =>
      await createIfNotExists.call(previews, params),
  };
}

function adaptBlaxelDriveApi(drives: unknown): BlaxelDriveApi | undefined {
  if (!isRecord(drives)) {
    return undefined;
  }
  const mount = drives.mount;
  if (typeof mount !== 'function') {
    return undefined;
  }
  const unmount = drives.unmount;
  if (!('list' in drives)) {
    return {
      mount: async (driveName, mountPath, drivePath, readOnly) =>
        await mount.call(drives, driveName, mountPath, drivePath, readOnly),
      unmount: async (mountPath) =>
        typeof unmount === 'function'
          ? await unmount.call(drives, mountPath)
          : undefined,
    };
  }
  const sdkDrives =
    drives as unknown as import('@blaxel/core').SandboxInstance['drives'];
  return {
    mount: async (driveName, mountPath, drivePath, readOnly) =>
      await mount.call(sdkDrives, {
        driveName,
        mountPath,
        ...(drivePath ? { drivePath } : {}),
        readOnly,
      }),
    unmount: async (mountPath) =>
      typeof unmount === 'function'
        ? await unmount.call(sdkDrives, mountPath)
        : undefined,
  };
}

function blaxelReadError(path: string, error: unknown): Error {
  if (error instanceof SandboxProviderError) {
    return error;
  }
  const cause = providerErrorMessage(error);
  const details = { provider: 'blaxel', path, cause };
  if (isBlaxelReadNotFoundError(cause)) {
    return new SandboxWorkspaceReadNotFoundError(
      `Blaxel sandbox file not found: ${path}`,
      details,
    );
  }
  return new SandboxWorkspaceArchiveReadError(
    `Blaxel sandbox failed to read file: ${path}`,
    details,
  );
}

function isBlaxelReadNotFoundError(message: string): boolean {
  const lower = message.toLowerCase();
  return (
    lower.includes('no such file or directory') ||
    lower.includes('not found') ||
    lower.includes('enoent')
  );
}

function toBlaxelTimeoutSeconds(
  timeoutMs: number | undefined,
): number | undefined {
  if (timeoutMs === undefined) {
    return undefined;
  }
  return Math.ceil(timeoutMs / 1000);
}

function buildShellCommand(
  command: string,
  environment: Record<string, string>,
): string {
  const exports = Object.entries(environment).map(([key, value]) => {
    assertShellEnvironmentName(key);
    return `export ${key}=${shellQuote(value)}`;
  });
  if (exports.length === 0) {
    return command;
  }
  return [...exports, command].join(' && ');
}

function remoteWriteTempPath(path: string): string {
  const dir = posixDirname(path);
  const prefix = dir === '/' ? '' : dir;
  return `${prefix}/.openai-agents-write-${randomUUID()}`;
}

function resolveBlaxelTimeouts(
  options: Pick<
    BlaxelSandboxClientOptions,
    'timeoutMs' | 'createTimeoutMs' | 'timeouts'
  >,
): BlaxelSandboxTimeouts {
  return {
    ...options.timeouts,
    execTimeoutMs: options.timeouts?.execTimeoutMs ?? options.timeoutMs,
    createTimeoutMs:
      options.timeouts?.createTimeoutMs ?? options.createTimeoutMs,
    workspaceTarTimeoutMs:
      options.timeouts?.workspaceTarTimeoutMs ?? options.timeoutMs,
    fastOperationTimeoutMs:
      options.timeouts?.fastOperationTimeoutMs ?? options.timeoutMs,
  };
}

async function withBlaxelOperationTimeout<T>(
  operation: Promise<T>,
  timeoutMs: number | undefined,
  operationName: string,
  options: { onTimeout?: () => void } = {},
): Promise<T> {
  if (typeof timeoutMs !== 'number') {
    return await operation;
  }

  let timeoutId: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<never>((_, reject) => {
    timeoutId = setTimeout(() => {
      options.onTimeout?.();
      reject(
        new SandboxProviderError(
          `BlaxelSandboxClient ${operationName} timed out after ${timeoutMs}ms.`,
          {
            provider: 'blaxel',
            operation: operationName,
            timeoutMs,
          },
        ),
      );
    }, timeoutMs);
  });
  try {
    return await Promise.race([operation, timeout]);
  } finally {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
  }
}

function extractBlaxelSandboxUrl(sandbox: unknown): string | undefined {
  if (!isRecord(sandbox)) {
    return undefined;
  }
  const directUrl = sandbox.url;
  if (typeof directUrl === 'string') {
    return directUrl;
  }
  const nestedSandbox = sandbox.sandbox;
  if (!isRecord(nestedSandbox)) {
    return undefined;
  }
  const metadata = nestedSandbox.metadata;
  if (!isRecord(metadata) || typeof metadata.url !== 'string') {
    return undefined;
  }
  return metadata.url;
}

function buildBlaxelPtyWebSocketUrl(args: {
  sandboxUrl: string;
  token: string;
  sessionId: string;
  cwd: string;
  cols?: number;
  rows?: number;
}): string {
  const base = args.sandboxUrl.replace(/\/$/u, '');
  const wsBase = base.replace(/^https:/u, 'wss:').replace(/^http:/u, 'ws:');
  const params = new URLSearchParams({
    token: args.token,
    cols: String(args.cols ?? 80),
    rows: String(args.rows ?? 24),
    sessionId: args.sessionId,
    workingDir: args.cwd,
  });
  return `${wsBase}/terminal/ws?${params.toString()}`;
}

function handleBlaxelPtyMessage(entry: PtyProcessEntry, event: unknown): void {
  const text = webSocketEventText(event);
  if (!text) {
    return;
  }
  let payload: unknown;
  try {
    payload = JSON.parse(text);
  } catch {
    return;
  }
  if (!isRecord(payload)) {
    return;
  }
  const type = payload.type ?? payload.Type;
  if (type === 'output') {
    const data = payload.data ?? payload.Data;
    if (typeof data === 'string') {
      appendPtyOutput(entry, data);
    }
    return;
  }
  if (type === 'error') {
    const data = payload.data ?? payload.Data;
    if (typeof data === 'string') {
      appendPtyOutput(entry, data);
    }
    markPtyDone(entry, 1);
  }
}

function blaxelPtyCloseExitCode(
  entry: PtyProcessEntry,
  event: unknown,
): number {
  if (entry.exitCode !== null) {
    return entry.exitCode;
  }
  return webSocketCloseCode(event) === 1000 ? 0 : 1;
}

function webSocketCloseCode(event: unknown): number | undefined {
  if (typeof event === 'number') {
    return event;
  }
  if (!isRecord(event)) {
    return undefined;
  }
  const code = event.code ?? event.data;
  return typeof code === 'number' ? code : undefined;
}

function extractBlaxelPreviewUrl(preview: unknown): string | undefined {
  if (!isRecord(preview)) {
    return undefined;
  }

  for (const nested of ['spec', 'status'] as const) {
    const value = preview[nested];
    if (isRecord(value) && typeof value.url === 'string' && value.url) {
      return value.url;
    }
  }

  for (const key of ['url', 'endpoint'] as const) {
    const value = preview[key];
    if (typeof value === 'string' && value) {
      return value;
    }
  }

  return extractBlaxelPreviewUrl(preview.preview);
}

async function createBlaxelPreviewTokenQuery(
  preview: unknown,
  ttlSeconds: number,
  port: number,
): Promise<string> {
  const tokens = findBlaxelPreviewTokens(preview);
  if (!tokens) {
    throw new SandboxProviderError(
      'BlaxelSandboxClient private previews require a preview token API.',
      {
        provider: 'blaxel',
        port,
      },
    );
  }

  const createToken = tokens.create;
  if (typeof createToken !== 'function') {
    throw new SandboxProviderError(
      'BlaxelSandboxClient private previews require tokens.create().',
      {
        provider: 'blaxel',
        port,
      },
    );
  }

  let token: unknown;
  try {
    token = await createToken.call(
      tokens,
      new Date(Date.now() + Math.max(1, ttlSeconds) * 1000),
    );
  } catch (error) {
    throw new SandboxProviderError(
      `BlaxelSandboxClient failed to create a private preview token for port ${port}.`,
      {
        provider: 'blaxel',
        port,
        cause: providerErrorMessage(error),
      },
    );
  }

  const tokenValue =
    typeof token === 'string'
      ? token
      : isRecord(token) && typeof token.value === 'string'
        ? token.value
        : isRecord(token) && typeof token.token === 'string'
          ? token.token
          : undefined;
  if (!tokenValue) {
    throw new SandboxProviderError(
      'BlaxelSandboxClient private preview token response did not include a token value.',
      {
        provider: 'blaxel',
        port,
      },
    );
  }

  return new URLSearchParams({
    bl_preview_token: tokenValue,
  }).toString();
}

function findBlaxelPreviewTokens(
  preview: unknown,
  seen: Set<object> = new Set(),
): Record<string, unknown> | undefined {
  if (!isRecord(preview)) {
    return undefined;
  }
  if (seen.has(preview)) {
    return undefined;
  }
  seen.add(preview);

  if (isRecord(preview.tokens)) {
    return preview.tokens;
  }

  return findBlaxelPreviewTokens(preview.preview, seen);
}

function webSocketEventText(event: unknown): string | undefined {
  const data =
    event && typeof event === 'object' && 'data' in event
      ? (event as { data?: unknown }).data
      : event;
  if (typeof data === 'string') {
    return data;
  }
  if (data instanceof ArrayBuffer) {
    return new TextDecoder().decode(data);
  }
  if (ArrayBuffer.isView(data)) {
    return new TextDecoder().decode(
      new Uint8Array(data.buffer, data.byteOffset, data.byteLength),
    );
  }
  return undefined;
}
