
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.11.6",
  "versions": {
    "@openai/agents-core": "0.11.6",
    "openai": "^6.35.0"
  }
};

export default METADATA;
